### ISSUE TITLE
time.clock() deprecated since Python 3.3, must be updated for 3.8

### ISSUE THREAD

**Issue by neilsmurphy** [backtrader2/backtrader#2]
The function time.clock() has been removed, after having been deprecated since Python 3.3: 
Causing failure in testing with 3.8. (ref. [StackOverflow]()https://stackoverflow.com/questions/58569361/attributeerror-module-time-has-no-attribute-clock-in-python-3-8)

use time.perf_counter() or time.process_time() instead, depending on your requirements, to have well-defined behavior. (Contributed by Matthias Bussonnier in bpo-36895.)

**Comment by vladisld** [comment]
Closing this issue since it was resolved in #4
