### ISSUE TITLE
[bug]bt.Analyzer.AnnualReturn is not right when it is not used the timeframe "daily"

### ISSUE THREAD

**Issue by tianjixuetu** [backtrader2/backtrader#23]
I test this class AnnualReturn, and I find,when the bar is daily,it is right,when the bar is below daily,for example 15min bar,the annual return is not right.

**Comment by ab-trader** [comment]
Please provide the sample script which recreates the issue, actual results and expected results.

**Comment by tianjixuetu** [comment]
ok,thank you for your reminder

**Comment by neilsmurphy** [comment]
@tianjixuetu Is this still an outstanding issue?

**Comment by tianjixuetu** [comment]
@neilsmurphy  yes,it is，and according to the backtrader's docs,the AnnualReturn is depleted and I use a new analyzer to solve it,but my backtrader's code is very different from the original source code,so,I need some time to fix it.

**Comment by neilsmurphy** [comment]
> and according to the backtrader's docs,the AnnualReturn is depleted

Thanks for the update, let us know if you get some data showing the error. Where did you see that AnnualReturn is depleted?

**Comment by tianjixuetu** [comment]
well,I try to look for  this message from the docs and source code, I cannot get it ，but in my memory, I know this analyzer is depleted,althougth we can find it in the source code.
the simplest way is just have a try,try and we can know whether it is  a error.

**Comment by tianjixuetu** [comment]
@neilsmurphy  I'm very sorry that I cannot find this bug. my test code is 
`from __future__ import (absolute_import, division, print_function,
                        unicode_literals)
import time 
import datetime  
import os
import sys  
import backtrader as bt
import numpy as np
import pandas as pd
import random


    
# 编写策略
class test_annualreturn(bt.Strategy):
    """buy in the first bar and sell in the last bar and calculate the annualreturn"""

    def log(self, txt, dt=None):
        ''' Logging function fot this strategy'''
        dt = dt or self.datas[0].datetime.date(0)
        print('%s, %s' % (dt.isoformat(), txt))

    def __init__(self):
        # Keep a reference to the "close" line in the data[0] dataseries
        self.bar_num = 0
        # 保存净值
        self.result = []
        
    
        
    def prenext(self):
        
        pass 
        
    def next(self):
        # every bar add one
        self.bar_num+=1
        self.log(self.bar_num)
        self.result.append([self.datas[0].datetime.datetime(0),self.broker.get_value()])
        # 得到资金
        if self.bar_num==1:
            self.buy(self.datas[0],size=10)
            
    def stop(self):
        df = pd.DataFrame(self.result)
        df.columns=['datetime','total_value']
        df.to_csv("/home/yun/test_annual_ret.csv")
        
            
        
    '''    
    def notify_order(self, order):
        if order.status in [order.Submitted, order.Accepted]:
            # Buy/Sell order submitted/accepted to/by broker - Nothing to do
            return

        # Check if an order has been completed
        # Attention: broker could reject order if not enougth cash
        if order.status in [order.Completed, order.Canceled, order.Margin]:
            if order.issell():
                self.log(
                    'sell EXECUTED, Price: %.2f, Cost: %.2f, Comm %.2f' %
                    (order.executed.price,
                     order.executed.value,
                     order.executed.comm))
           
            else:  # Sell
                self.log('buy EXECUTED, Price: %.2f, Cost: %.2f, Comm %.2f' %
                         (order.executed.price,
                          order.executed.value,
                          order.executed.comm))
            
                

    def notify_trade(self, trade):
        if trade.isclosed:
            
            self.log('TRADE PROFIT, GROSS %.2f, NET %.2f' %
                     (trade.pnl, trade.pnlcomm))
    '''
begin_time=time.time()
cerebro = bt.Cerebro()
# cerebro.broker = bt.brokers.BackBroker()  # 0.5%
# cerebro.broker.set_slippage_fixed(1, slip_open=True)
# Add a strategy
# cerebro.addstrategy(grid_strategy)
    # 优化参数
    #strats = cerebro.optstrategy(
    #    momentum_strategy,
    #    look_back_days=[5,10],
    #    hold_days=[5,10,15,20],
    #    hold_percent=[0.1,0.2])
    # Datas are in a subfolder of the samples. Need to find where the script is
    # because it could have been called from anywhere
tbquant_1h_kwargs = dict(
            fromdate = datetime.datetime(2010, 1, 4),
            todate = datetime.datetime(2020, 3, 19),
            timeframe = bt.TimeFrame.Minutes,
            compression = 1,
            dtformat=('%Y-%m-%d %H:%M:%S'),
            datetime=2,
            high=5,
            low=6,
            open=4,
            close=7,
            volume=8,
            openinterest=9
            )

data_path="/home/yun/tbquant_rb000.SHFE_1h.csv"
feed=bt.feeds.GenericCSVData(dataname=data_path,**tbquant_1h_kwargs)
cerebro.adddata(feed)
cerebro.broker.setcommission(commission=0)
cerebro.broker.setcash(100000.0)
cerebro.addstrategy(test_annualreturn)
cerebro.addanalyzer(bt.analyzers.AnnualReturn, _name='annualreturn')
results=cerebro.run()`

the data can be download at this link:
`链接: https://pan.baidu.com/s/142xkTNjrVwqY3D1VfS6atg 提取码: 2v4z`

**Comment by tianjixuetu** [comment]
I also test the precious strategy which I run in my company,but cannot find this bug again,so,I decide to close this issue. I'm very sorry for that this  Invalid bug waste your time.
