### ISSUE TITLE
Yahoo 'no such file or directory error'

### ISSUE THREAD

**Issue by neilsmurphy** [backtrader2/backtrader#3]
Taken from bt issues: 
Prevent YahooFinanceData from throwing No such file or directory: since Yahoo's response type has changed

For [context](https://community.backtrader.com/topic/2363/errno-2-no-such-file-or-directory/)

It's unfortunate because it breaks the example on the page at [https://www.backtrader.com/home/helloalgotrading/](https://www.backtrader.com/home/helloalgotrading/)

**Comment by ronnyli** [comment]
Port over yinghang's PR: https://github.com/mementum/backtrader/pull/401 (I'll do it after waiting 24hrs for the original author)

**Comment by vladisld** [comment]
Closing this issue, since it was fixed in #4
