### ISSUE TITLE
cerebro.plot() aquivalent for plotly

### ISSUE THREAD

**Issue by lechner-philipp** [backtrader2/backtrader#63]
I would like to contribute to backtrader with an addition for plotting.

Personally I like using plotly over matplotlib because I find it more flexible.
I already coded a decent equivalent of the `cerebro.plot()` function with plotly and was curious if it's a feature more people are interested in. If so I polish up my version and contribute it to backtrader.

**Comment by neilsmurphy** [comment]
Just an fyi, Backtrader is a closed project, and this project is really just for bug fixes. If you would like to share I would suggest putting a link in the community to your github repo. I look forward to seeing what you have come up with!
