### ISSUE TITLE
Use discussion feature of backtrader2/backtrader  in github

### ISSUE THREAD

**Issue by alatif-alatif** [backtrader2/backtrader#64]
Hi,

Github offers discussions for projects:
https://docs.github.com/en/discussions

I would suggest to open it for users of  `backtrader2/backtrader` , as the old forum https://community.backtrader.com does get more and more issues (e.g.: people sometimes cannot reply, posting date is not shown anymore, editing a post was never possible etc.)

What do you think?

**Comment by neilsmurphy** [comment]
Thanks for the feedback. I don't think I'm in favour of this suggestion at this time. Backtrader2 was meant to be a place to do bug fixes, not take over the backtrader project. The community forum has lots of traction and history. I think a better effort would be to get Daniel to share/open up the community to others to help manage so any bug fixes could be dealth with.
